name: AS

on:
  repository_dispatch:
    types: [ci-complete]
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

  workflow_dispatch:

jobs:

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    # Only deploy when CI was successful
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Install Ansible Docker collection
        run: |
          ansible-galaxy collection install community.docker

      - name: Configure SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > docker.pem
          chmod 400 docker.pem

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}
      
      - name: Get EC2 public IP
        id: ec2_ip
        run: |
          cd terraform
          terraform init -input=false -backend-config="region=eu-north-1"
      
          EC2_IP=$(terraform output -raw instance_public_ip)
      
          echo "EC2_IP=$EC2_IP" >> "$GITHUB_ENV"

      - name: Create Ansible inventory
        run: |
          mkdir -p ansible/inventory

          cat > ansible/inventory/hosts.ini <<EOF
          [webservers]
          ec2 ansible_host=${EC2_IP} ansible_user=ubuntu ansible_ssh_private_key_file=$GITHUB_WORKSPACE/docker.pem
          EOF

          cat ansible/inventory/hosts.ini

      - name: Test Ansible connection
        run: |
          ansible -i ansible/inventory.ini webservers -m ping

      - name: Configure EC2 and install Docker
        run: |
          ansible-playbook \
            -i ansible/inventory.ini \
            ansible/config.yaml

      - name: Deploy website
        run: |
          ansible-playbook \
            -i ansible/inventoryini \
            ansible/deploy.yaml
          

          
          echo "================================="
          echo "Deployment completed successfully"
          echo "================================="
